version: '3.8'
services:
  nginx_http:
    image: nginx:alpine
    container_name: nginx_http
    volumes:
      - ./nginx/nginx.http.conf:/etc/nginx/conf.d/default.conf:ro
      - certbot_data:/var/www/certbot
    ports:
      - "80:80"
    networks:
      - ssl_network

  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    command: >- 
             certonly --webroot --webroot-path=/var/www/certbot
             --email ${EMAIL} --agree-tos --no-eff-email
             ${DOMAINS} --expand --non-interactive --quiet
    volumes:
      - letsencrypt_data:/etc/letsencrypt
      - certbot_data:/var/www/certbot
    depends_on:
      - nginx_http
    networks:
      - ssl_network

  nginx_https:
    image: nginx:alpine
    container_name: nginx_https
    volumes:
      - ./nginx/nginx.https.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/proxy_params:/etc/nginx/proxy_params:ro
      - letsencrypt_data:/etc/letsencrypt:ro
      - dhparam_data:/etc/ssl/certs
    ports:
      - "443:443"
    depends_on:
      - certbot
    networks:
      - ssl_network

  docker_ssl_manager:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - EMAIL=${EMAIL}
      - DOMAINS=${DOMAINS}
      - DOMAIN1_RENEW_MINUTE=${DOMAIN1_RENEW_MINUTE}
      - DOMAIN1_RENEW_HOUR=${DOMAIN1_RENEW_HOUR}
      - DOMAIN1_RENEW_DAY=${DOMAIN1_RENEW_DAY}
      - DOMAIN1_RENEW_MONTH=${DOMAIN1_RENEW_MONTH}
      - DOMAIN1_RENEW_DAY_OF_WEEK=${DOMAIN1_RENEW_DAY_OF_WEEK}
      - DOMAIN2_RENEW_MINUTE=${DOMAIN2_RENEW_MINUTE}
      - DOMAIN2_RENEW_HOUR=${DOMAIN2_RENEW_HOUR}
      - DOMAIN2_RENEW_DAY=${DOMAIN2_RENEW_DAY}
      - DOMAIN2_RENEW_MONTH=${DOMAIN2_RENEW_MONTH}
      - DOMAIN2_RENEW_DAY_OF_WEEK=${DOMAIN2_RENEW_DAY_OF_WEEK}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certbot_data:/var/www/certbot
      - letsencrypt_data:/etc/letsencrypt
      - dhparam_data:/etc/ssl/certs
    depends_on:
      - nginx_https
    networks:
      - ssl_network

  dhparam_generator:
    image: nginx:alpine
    command: sh -c "if [ ! -f /etc/ssl/certs/dhparam.pem ]; then openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048; fi"
    volumes:
      - dhparam_data:/etc/ssl/certs

volumes:
  certbot_data:
  letsencrypt_data:
  dhparam_data:

networks:
  ssl_network:
    driver: bridge